load("@rules_helm//helm:defs.bzl", "helm_chart", "helm_template")

# kind delete clusters --all
# bazel run //:load-image
# kind create cluster
# bazel run //helm-chart:chart.install

# //helm-chart:chart
# //helm-chart:chart.install
# //helm-chart:chart.push_images
# //helm-chart:chart.uninstall
# //helm-chart:chart.upgrade
helm_chart(
    name = "chart",
    chart = "Chart.yaml",
    templates = glob(["templates/**/*.yaml"]),
    values = "values.yaml",
    visibility = ["//visibility:public"],
)

# bazel build //helm-chart:rendered_chart
# kubectl apply -f bazel-bin/helm-chart/rendered_chart.yaml
helm_template(
    name = "rendered_chart",
    chart = ":chart",
    visibility = ["//visibility:public"],
)
