# Default values for hello-k8s
replicaCount: 2

image:
  repository: "{{//app:deploy_image_index}}"
  tag: ""
  pullPolicy: Always  # Pull from registry pushed by k8s_deploy

appName: hello-k8s-helm

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests:
    memory: "32Mi"
    cpu: "50m"
  limits:
    memory: "64Mi"
    cpu: "100m"

livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5
